title: Hey, my name is Gerard
author: Gerard Casas Saez
color: "#2B546B"
description: |
  I'm a Senior ML Engineer. I'm specially interested in Machine Learning Infrastructure and Data Engineering. 
  I graduated from <a href="https://www.colorado.edu/" target="_blank">University of Colorado Boulder</a> in 2019. 
  In my free time I like to ski, take pictures and read some books.
  Follow me on <a href="https://twitter.com/casassaez" target="_blank">Twitter</a> to stay updated on my latest adventures.
domain: gerard.space
twitter: casassaez
mastodon: macaw.social/@gerard
sass:
    sass_dir: assets/_sass
    style: compressed
include: [".well-known"]

plugins:
  - jekyll-redirect-from
